#!/usr/bin/env node
/**
 * compile-content.mjs — validate + emit authored JSON content.
 *
 * Reads config/raw/{biomes,creatures,landmarks}/*.json, validates
 * each file against its Zod schema, and emits a single typed TS
 * module at config/compiled/content.ts. Importing consumers see the
 * tables as readonly arrays of their typed records.
 *
 * Runs as a `prebuild` and `predev` step so authored content edits
 * are reflected in the running app without a manual build.
 */

import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..");
const rawRoot = join(repoRoot, "config/raw");
const compiledRoot = join(repoRoot, "config/compiled");

const BiomeSchema = z.object({
  id: z.enum(["photic-gate", "twilight-shelf", "midnight-column", "abyssal-trench"]),
  label: z.string().min(1),
  description: z.string().min(1),
  depthStartMeters: z.number().int().min(0),
  depthEndMeters: z.number().int().positive(),
  tintHex: z.string().regex(/^#[0-9a-fA-F]{6}$/),
  creatureDensity: z.number().min(0).max(2),
  predatorDensity: z.number().min(0).max(2),
  pirateDensity: z.number().min(0).max(2),
});

const CreatureSpeciesSchema = z.object({
  id: z.string().min(1),
  type: z.enum(["jellyfish", "plankton", "fish"]),
  baseScore: z.number().int().nonnegative(),
  oxygenBonusSeconds: z.number().int().nonnegative(),
  glowColor: z.string().regex(/^#[0-9a-fA-F]{6}$/),
  color: z.string().regex(/^#[0-9a-fA-F]{6}$/),
  sizeMeters: z.object({
    min: z.number().positive(),
    max: z.number().positive(),
  }),
});

const LandmarkSchema = z.object({
  id: z.string().min(1),
  label: z.string().min(1),
  depthMeters: z.number().int().positive(),
  biome: z.enum(["photic-gate", "twilight-shelf", "midnight-column", "abyssal-trench"]),
  flavor: z.string().min(1),
});

function loadDir(dir, schema, kind) {
  const files = readdirSync(dir).filter((f) => f.endsWith(".json")).sort();
  const out = [];
  for (const file of files) {
    const full = join(dir, file);
    const raw = JSON.parse(readFileSync(full, "utf8"));
    const parsed = schema.safeParse(raw);
    if (!parsed.success) {
      console.error(`[compile-content] ${kind} file ${file} failed validation:`);
      console.error(parsed.error.issues);
      process.exit(1);
    }
    out.push(parsed.data);
  }
  return out;
}

const biomes = loadDir(join(rawRoot, "biomes"), BiomeSchema, "biome");
const creatures = loadDir(join(rawRoot, "creatures"), CreatureSpeciesSchema, "creature");
const landmarks = loadDir(join(rawRoot, "landmarks"), LandmarkSchema, "landmark");

// Sort tables so the order in the generated file is deterministic
// and matches gameplay expectation. Biomes by depthStartMeters;
// landmarks too.
biomes.sort((a, b) => a.depthStartMeters - b.depthStartMeters);
landmarks.sort((a, b) => a.depthMeters - b.depthMeters);
creatures.sort((a, b) => a.baseScore - b.baseScore);

mkdirSync(compiledRoot, { recursive: true });
const body = `// Generated by scripts/compile-content.mjs. Do not edit by hand.
// Source of truth: config/raw/{biomes,creatures,landmarks}/*.json.

export const COMPILED_BIOMES = ${JSON.stringify(biomes, null, 2)} as const;
export const COMPILED_CREATURES = ${JSON.stringify(creatures, null, 2)} as const;
export const COMPILED_LANDMARKS = ${JSON.stringify(landmarks, null, 2)} as const;
`;
writeFileSync(join(compiledRoot, "content.ts"), body);
console.log(
  `[compile-content] wrote content.ts: ${biomes.length} biomes, ${creatures.length} creatures, ${landmarks.length} landmarks`
);
